### ISSUE TITLE
Get the logo design in game

### ISSUE THREAD

**Issue by imdaveead** [WeAreDevs/material-clicker#16]
Use the logo in #2 and place it everywhere needed.

Places logo needs placement
- Documentation
  - Cover Page
  - Side bar
  - Browser Favicon
- Game
  - Title Bar
  - Electron EXE Icon

**Comment by hparcells** [comment]
Done in 75872f2c05163cc6d53466010f852e486d2d7b87.

**Comment by hparcells** [comment]
Reopened, adding automatic EXE icon changing.
