### ISSUE TITLE
More Sounds

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#18]
# Should Add
- [x] Shop Buy Sound

# Consider Adding
- [x] Tab Switch Sound (maybe like a *woosh*)
- [x] Golden Click Sound

**Comment by imdaveead** [comment]
for golden click sound, that should totally be added, maybe as a pop sound or something.

**Comment by hparcells** [comment]
Golden Click sound done in d6cde582268e46af0a774086fe59d5a966e001bc

**Comment by hparcells** [comment]
Tab Change Sound Partially Done in 39aa752b75bf8012b3d6bc3ebb39b5ffc632d10e

- [ ] Play the sound on tab change by clicking the tab.
- [ ] Shift + Tab doesn't work. See #24, but still plays sound.
