### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [WeAreDevs/material-clicker#2]
Hi, I'm a logo designer I just saw your project and if you want I can design a free logo for your project. So, what do you say?

**Comment by imdaveead** [comment]
That was something we were thinking about doing soon, but since neither of us are actually good at that stuff, you could try that out.

what i'm looking for:
- something **very simple**
- using white (#ffffff) and the material design blue 500 (#2196f3)
- square, good quality, transperent

I hope this can be achievable

**Comment by hparcells** [comment]
@imdaveead the resolution for Electron is 64x64. So we need that size. Do you think you want a bigger size, say 512x512 for the documentation and README?

**Comment by imdaveead** [comment]
> @imdaveead the resolution for Electron is 64x64. So we need that size. Do you think you want a bigger size, say 512x512, for the documentation and README?

i forgot about the readme/docs, but i'm seeing two spots a logo is needed: the titlebar and the executable's icon. it really doesnt matter since it can be scaled down or up, AND: if it's a svg we can scale it to any size we want.

**Comment by hparcells** [comment]
> **edit**: You can upload a logo to the repo in `./src/game/content/image/<here>`, you may need to create that folder.

Instead of the content folder, you want it to be in a `res` folder, like `./src/game/res/img/<here>`.

**Comment by imdaveead** [comment]
I know it's only been two days, but we work on a very fast schedule. If you cannot get something in less than one day I will probably make my own logo. After that, you can design a different logo, but that may not be needed.

**Comment by tebriz159** [comment]
Sorry for late I was busy, I made a design, here's all the files about the logo.

![pr2](https://user-images.githubusercontent.com/31902754/52885604-a350a380-3126-11e9-9f39-fe03358fa806.png)

I used mouse cursor icon to give meaning to clicker and combined with the first letters of Material Clicker. Hope you like it )


![pr1](https://user-images.githubusercontent.com/31902754/52885708-f9bde200-3126-11e9-8db2-9c37a376a1a3.png)

**Comment by hparcells** [comment]
Thank you for the icons and art! We appreciate it! They look really nice! We will be sure to credit you in the game somewhere.

**Comment by imdaveead** [comment]
I'll work on adding these to the game in a second. Thank you for the design.
