### ISSUE TITLE
Fading Numbers Above Click Point

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#20]
Similar to Cookie Clicker, it displays the number of Material you got, flies up, and fade out.

![2019-02-16_13-53-16](https://user-images.githubusercontent.com/40444294/52903890-3b678f00-31f2-11e9-9f84-ba0d58a1da1d.gif)

**Comment by imdaveead** [comment]
What if this also happened with material generators like auto clicker or bomb? in a similar effect.
