### ISSUE TITLE
Stats System

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#27]
This can maybe be a page in the File button, or another tab itself. It would show nice data such as:
- [x] How many times you clicked the button.
- [x] How much Material you gained in your lifetime.
- [x] How much Materials you spent in your lifetime.
- [x] Upgrades bought.
- [ ] How many times you prestiged.
- [ ] How much Golden Material you got in your lifetime.
- [ ] How much Golden Material you spent in your lifetime.
- [x] Time played.
- [ ] Cases opened.

This will not be reset on prestige.

**Comment by hparcells** [comment]
First three stats done in 9fbf09613e233701b4f00dbdf0e901b06983cb8a with a Stats page.

**Comment by imdaveead** [comment]
Closing for now due to the rest of the stats cannot be tracked due to the feature they revolve around not existing yet.
