### ISSUE TITLE
Display on the shop your current material count.

### ISSUE THREAD

**Issue by imdaveead** [WeAreDevs/material-clicker#33]
I see two ways of doing this.

- add in the titlebar as it was pre-custom-titlebar
- add it in the shop panel

I think we should go for the titlebar, and maybe even insert it to the right of the logo before the menu as a super small number (such as `4K` or `2.5M`), which would use a different number compactor.

**Comment by imdaveead** [comment]
So i added it to the titlebar, but i'd want to see how it looks if moved to the left of the menu

**Comment by hparcells** [comment]
I thought we had a parameter to say how many decimal places we want to display, so we don't need another number compactor.

**Comment by hparcells** [comment]
**Closed**. The Material count is displayed in the titlebar.
