### ISSUE TITLE
Revise and Add new Sounds

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#37]
- [x] Better Golden Click Sound
- [x] Milestone Reach Sound
- [x] More click sounds, which can be set in customization settings. (this doesn't need to be implemented yet, just finding them)
- [x] Achievement sound (if we decide to add achievements)

**Comment by imdaveead** [comment]
Lets try to find some more sounds that people can buy or unlock, even if thats not a feature yet.

**Comment by imdaveead** [comment]
more sounds arent going to be available in game just yet, or are they? i'm going to close this since all the missing sounds are already found.
