### ISSUE TITLE
New Cases

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#47]
- [ ] Powerup Case
Gives you powerups. Needs #48 Powerup System.
- [x] Russian Roulette Case
Has a 1/6th chance of doubling your current Material count. If not, takes half your clicks.
- [x] True Russian Roulette Case
Has a 1/6th chance of multiplying your current Material count by five, if not, takes ALL your clicks.
- [x] 50/50 Case
Has a 50/50 chance of doubling or taking half your Material.
- [x] Case Case
Gives you cases.

**Comment by hparcells** [comment]
Russian Roulette Cases and 50/50 Case done in 68cf7c67ca8d2f077aedbdb83866c0e453b2bc73.

**Comment by hparcells** [comment]
Case Case done in 401be80f89a7fae4083177231f6422725e54cead.

**Comment by imdaveead** [comment]
Since the powerup system is not going to be added in 1.2.0 i'm going to close it so we can get 1.2.0 done
