### ISSUE TITLE
Test the Save and Load to make sure it is stable

### ISSUE THREAD

**Issue by imdaveead** [WeAreDevs/material-clicker#5]
I was having some troubles with savefile corruption, but I think most of those are solved.

**Comment by hparcells** [comment]
Close Using Titlebar X: 👍 
Close Using File -> Exit: 👍 
Alt + F4: 👎 
Task Manager Kill: 👎

**Comment by hparcells** [comment]
Close By Right Clicking App In Taskbar -> Close: 👎 
Close By Ctrl + C'ing the Process: 👎

**Comment by imdaveead** [comment]
wait a second alt f4 doesnt work? nevermind closing this

**Comment by imdaveead** [comment]
Very odd, saving works for me with Alt+F4

**Comment by hparcells** [comment]
I used Windows 10. So that might change something.
