### ISSUE TITLE
Cases Don't Reset on Game Save Delete

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#58]
![image](https://user-images.githubusercontent.com/40444294/53921672-48341180-403f-11e9-9d9d-36b0f1decfdf.png)

**Comment by imdaveead** [comment]
thats odd, since deleting your savefile in settings does the following
- disable autosave on exit
- delete the tracked savefile `.json` files
- refresh the browserwindow

so theres no way it should have access to any old save file.

**Comment by hparcells** [comment]
I even deleted the save folder itself. Could it be something hard coded?

**Comment by imdaveead** [comment]
I just realized that i never pushed the code which is in 1.2.9 which fixes a different issue that causes this, it's with the todoResolve function. please pull the new code.
