### ISSUE TITLE
Cases System

### ISSUE THREAD

**Issue by imdaveead** [WeAreDevs/material-clicker#7]
Make a version of SomeClicker's Case system, which itself is a copy of CSGO's cases (if i remember correctly)

To-do:
- [X] Random Collection from SC
- [x] Case Content File
- [x] Registering case files
- [x] Case Page (Tab)
- [x] Case Open Page
- [x] Animating the Case Page
- [x] Cases buying / obtaining.

It would be nice to have #31 done before adding the case buying

**Comment by hparcells** [comment]
Cases can contain Material or Sounds. You get these at Material milestones such as 1,000 Material, 2,000, and so on.

**Comment by imdaveead** [comment]
Going to move this to 1.2.0 as i want to release 1.1.0 as quick as i can.

**Comment by hparcells** [comment]
You want to not do this for 1.2 since we are working on other things, unless we are really close.

**Comment by imdaveead** [comment]
well, i moved the milestone's date a few more days. i think lets get this and the first case or two done.

**Comment by hparcells** [comment]
Case files and case registering done in 65bc641a6b02b1db537269462ae552fa644073b8.
