### ISSUE TITLE
Offline Material Production

### ISSUE THREAD

**Issue by imdaveead** [WeAreDevs/material-clicker#8]
When you open the app after not using it you gain some amount of material depending how long you've been away. There can maybe be limits to how much you can gain or how fast you gain it.

**Comment by hparcells** [comment]
Sure, we can add a limit. Also, there should be a small bonus for using offline production compared to keeping the game open for the same amount of time. Maybe something like 5%.

**Comment by hparcells** [comment]
The limit can be an upgrade in the shop.
